### ISSUE TITLE
Set custom size in px

### ISSUE THREAD

**Issue by 4n70w4** [Kristories/nova-qrcode-field#2]
Hi. qrcode generated with 50x50 px size. It's so small!
I want set custom size, for example 200x200 px

**Comment by Kristories** [comment]
[v0.0.3](https://github.com/Kristories/nova-qrcode-field/releases/tag/v0.0.3) released.
```
Qrcode::make('QR Code', 'url')
    ->indexSize(100)
    ->detailSize(500)
```
