### ISSUE TITLE
How to save qrcode to file?

### ISSUE THREAD

**Issue by 4n70w4** [Kristories/nova-qrcode-field#3]

**Comment by Dontorpedo** [comment]
same question, need to save the qrcode image to database

**Comment by Kristories** [comment]
@4n70w4 @Dontorpedo PR welcome!

**Comment by 4n70w4** [comment]
@Kristories  @Dontorpedo I made it easier, found a generator of qr-codes, save it in the database and display it as a image.

**Comment by Abdelhammied** [comment]
i do have this same isssue

**Comment by Kristories** [comment]
@Dontorpedo @4n70w4 We never store qr code image in database. A QR code is merely a way of representing a string of characters. Often people will put a URL into the QR code.

You can probably just store the source data into your db, and generate the QR from the data.

**Comment by Kristories** [comment]
@4n70w4 this is nova field. You can use [Bacon/BaconQrCode](https://github.com/Bacon/BaconQrCode) for it.
